const pt = {
  discover: "Descobrir",
  search: "Buscar",
  calendar: "Calendário",
  import: "Importar",
  settings: "Config",
  settingsPage: "Configurações",
  preferences: "Preferências",
  profile: "Perfil no daviandrade auth",
  guestEyebrow: "Sessão temporária",
  guestTitle: "Dá para usar tudo sem conta",
  guestLogin: "Entrar e salvar",
  guestContinue: "Continuar nesta sessão",
  work: "Meu trabalho",
  workBody:
    "Sou Davi Andrade. O Seriesaholic é um dos apps do portfólio, na mesma conta dos outros projetos.",
  student: "Asebili Aluno",
  instructor: "Asebili Instrutor",
  library: "Biblioteca",
  home: "Início",
  login: "Entrar",
  signOut: "Sair",
  toLight: "Ativar tema claro",
  toDark: "Ativar tema escuro",
  langPt: "Idioma: Português",
  langEn: "Idioma: Inglês",
  guestBody:
    "Adicionar séries, marcar episódios, descobrir e importar funciona agora. Isso fica só neste navegador e some quando a janela fechar. Entre para guardar na conta e abrir de novo quando quiser.",
  guestWork: "Seriesaholic faz parte do trabalho de Davi Andrade.",
  portfolio: "Portfólio",
  continueBrowsing: "Continuar sem entrar",
  newShow: "Nova série",
  newShowSubtitle: "Cadastre título, imagens, temporadas e episódios manualmente.",
  editShow: "Editar série",
  emptyLibrary: "Biblioteca vazia",
  emptyLibraryBody: "Importe seus dados do TV Time, descubra séries ou crie uma manualmente.",
  discoverShows: "Descobrir séries",
  createShow: "Criar série",
  importTvTime: "Importar TV Time",
  watchNow: "Assistir agora",
  backlog: "Atrasadas",
  upToDate: "Em dia",
  notStarted: "Adicionadas à lista",
  finished: "Finalizadas",
  dropped: "Interrompidas",
  seeAll: "Ver todas",
  seeAllNamed: "Ver todas — {title}",
  noPoster: "Sem poster",
  loadingUpcoming: "Buscando próximos episódios...",
  upcomingEpisodes: "Próximos episódios",
  forYou: "Para você",
  forYouBody: "Calculado a partir da sua biblioteca. Só busca quando você pedir.",
  calculating: "Calculando...",
  seeRecommendations: "Ver recomendações",
  noRecommendations: "Nenhuma recomendação com o que você já assistiu.",
  series: "Séries",
  episodes: "Episódios",
  time: "Tempo",
  fullStats: "Estatísticas completas",
  searchTitle: "Buscar séries",
  searchSubtitle: "Metadados via TMDB",
  searching: "Buscando...",
  inLibrary: "Na biblioteca",
  add: "Adicionar",
  wantToWatch: "Quero ver",
  adding: "Adicionando...",
  discoverTitle: "Descobrir",
  discoverBased: "Recomendado com base em {genres}",
  discoverCatalogCount: "{total} séries no catálogo, prontas para adicionar",
  discoverFallback: "Catálogo de séries populares do TMDB",
  syncing: "Sincronizando...",
  refreshCatalog: "Atualizar catálogo",
  loading: "Carregando...",
  loadingStats: "Carregando estatísticas...",
  discoverEmptyPersonal: "Importe suas séries do TV Time para receber recomendações personalizadas.",
  discoverEmpty: "Nenhuma série nova para descobrir.",
  fillCatalog: "Popular catálogo agora",
  tabAll: "Todas",
  tabTrending: "Em alta",
  tabPopular: "Populares",
  tabTop: "Top rated",
  match: "{n}% match",
  calendarTitle: "Calendário",
  calendarSubtitle: "Episódios dos próximos 30 dias",
  calendarEmpty: "Nenhum episódio programado. Adicione séries que você está assistindo.",
  statsTitle: "Estatísticas",
  statsSubtitle: "Seu histórico de consumo de séries",
  statsLoadError: "Erro ao carregar estatísticas",
  watchTime: "Tempo assistindo",
  watchTimeNone: "Sem histórico de episódios assistidos",
  watchTimeNoRuntime: "Sem duração cadastrada nos episódios",
  watchTimeLast7: "{hours} horas nos últimos 7 dias",
  hoursUnit: "Horas",
  episodesUnit: "Episódios",
  perWeekRuntime: "Por semana (só episódios com duração)",
  perWeek: "Por semana",
  perMonth: "Por mês",
  totalEpisodes: "Total de episódios",
  episodesLast7: "{n} nos últimos 7 dias",
  remainingEpisodes: "Episódios restantes",
  inStartedShows: "Em {n} séries iniciadas",
  catchUp: "Velocidade de catch-up",
  catchUpValue: "{n} ep/semana",
  catchUpBase: "Baseado nos últimos 2 meses",
  timeToWatch: "Tempo para assistir",
  futureAirtime: "Tempo futuro de exibição",
  addedShows: "Séries adicionadas",
  stillInProduction: "{n} ainda em produção",
  topGenres: "Top gêneros",
  genre: "Gênero",
  noGenres: "Importe séries para ver gêneros.",
  marathons: "Maiores maratonas",
  marathonShow: "Série",
  marathonEp: "Ep.",
  marathonHours: "Horas",
  noMarathons: "Nenhuma maratona registrada ainda.",
  settingsSubtitle: "Preferências e manutenção da biblioteca",
  dangerZone: "Zona de perigo",
  settingsDangerBefore: "Apaga",
  settingsDangerStrong: "todas as séries",
  settingsDangerAfter:
    ", progresso de episódios, séries custom e o histórico de importações. Use antes de um reimport limpo.",
  settingsItemLibrary: "Biblioteca e episódios assistidos",
  settingsItemImports: "Jobs e logs de import TV Time",
  settingsItemCatalogBefore: "O catálogo Discover (TMDB)",
  settingsItemCatalogNot: "não",
  settingsItemCatalogAfter: "é apagado",
  typeConfirm: "Digite {phrase} para habilitar:",
  erasing: "Apagando...",
  clearAll: "Limpar todos os dados",
  clearedBefore: "Dados limpos. Você pode",
  importAgain: "importar de novo",
  clearedOr: "ou voltar ao",
  clearedHome: "início",
  importTitle: "Importar do TV Time",
  importSubtitle: "Suporte a export GDPR, TV Time Liberator e JSON",
  viewHistory: "Ver histórico",
  clearData: "Limpar dados",
  importRunsOnServer:
    "A importação roda no servidor. Pode fechar ou atualizar esta página — o progresso continua e os dados já importados ficam salvos.",
  howToExport: "Como obter seus dados",
  importStep1Before: "Acesse",
  importStep1After: "e baixe seu export (arquivo .zip)",
  importStep2Before: "Alternativa: extensão",
  importStep2After: "(formato com IMDB/TVDB)",
  importStep3Before: "Configure sua TMDB API key no arquivo",
  importStep4: "Reimports adicionam só conteúdo novo, sem remover o que já existe",
  importStep5: "Faça upload do arquivo abaixo",
  filesSelected: "{n} arquivo(s) selecionado(s)",
  clickToSelect: "Clique para selecionar arquivos",
  importing: "Importando...",
  startImport: "Iniciar importação",
  pleaseWait: "Aguarde...",
  cancelImport: "Cancelar importação",
  cancelling: "Cancelando...",
  importDone: "Importação concluída",
  importCancelled: "Importação cancelada",
  importCancelledDetail: "Importação cancelada. O que já foi importado permanece na biblioteca.",
  importError: "Erro na importação",
  formatDetected: "Formato detectado",
  showsAdded: "Séries adicionadas",
  newEpisodes: "Episódios novos",
  alreadyExisted: "Já existiam",
  reviewAdded: "Conferir o que foi adicionado",
  phaseParsing: "Analisando arquivo",
  phaseEpisodes: "Importando episódios",
  phaseWatchlist: "Importando lista de desejos",
  phaseDropped: "Importando interrompidas",
  phaseStatus: "Finalizando",
  phaseComplete: "Concluído",
  notInLibrary: "Esta série ainda não está na sua biblioteca.",
  addToLibrary: "Adicionar à biblioteca",
  unknownError: "Erro desconhecido",
  edit: "Editar",
  deleting: "Deletando...",
  delete: "Deletar",
  saving: "Salvando...",
  dropShow: "Interromper série",
  resumeWatching: "Voltar a assistir",
  episodesHeading: "Episódios",
  deleteConfirm: "Deletar esta série e todo o progresso?",
  finishedLabel: "Finalizada",
  droppedLabel: "Interrompida",
  seasonName: "Temporada {n}",
  episodeName: "Episódio {n}",
  markAll: "Marcar tudo",
  unmarkAll: "Desmarcar tudo",
  formTitle: "Título",
  formStatus: "Status",
  formReturning: "Em produção",
  formEnded: "Finalizada",
  formCanceled: "Cancelada",
  formOverview: "Sinopse",
  formPoster: "Poster",
  formBackdrop: "Backdrop",
  formPremiere: "Estreia",
  formGenres: "Gêneros (separados por vírgula)",
  formSeasons: "Temporadas e episódios",
  formSeason: "Temporada",
  formName: "Nome",
  formNumber: "Nº",
  formAirDate: "Data",
  formRuntime: "Min",
  formEpisode: "Episódio",
  formSave: "Salvar alterações",
  formSaving: "Salvando...",
  formAddEpisode: "Episódio",
  finishedTitle: "Séries finalizadas",
  finishedCount: "{total} série(s) com todos os episódios assistidos",
  finishedEmpty: "Nenhuma série finalizada ainda.",
  backHome: "Voltar ao início",
  importsTitle: "Histórico de imports",
  importsSubtitle: "Registro de cada importação do TV Time",
  noImports: "Nenhum import registrado ainda.",
  firstImport: "Fazer primeiro import",
  showsAddedShort: "+{n} séries",
  alreadyExistedShort: "({n} já existiam)",
  importBack: "Voltar ao histórico",
  importOf: "Import de {date}",
  newShows: "Séries novas",
  episodesAdded: "Episódios adicionados",
  uniqueErrors: "Erros únicos",
  uniqueWarningCount: "{n} avisos únicos",
  showsInImport: "Séries deste import ({n})",
  noNewShows: "Nenhuma série nova neste import.",
  episodesAddedCount: "+{n} episódio(s)",
  failuresTitle: "Falhas de importação ({n} pendente(s))",
  failuresBody:
    "Cada linha abaixo indica exatamente o que não entrou. Assimile a uma série da biblioteca ou crie uma nova para gravar os episódios assistidos.",
  searchShow: "Buscar série",
  notFoundTitle: "Página não encontrada",
  notFoundBody: "Esse endereço não existe ou o conteúdo foi removido.",
  errorTitle: "Algo deu errado",
  errorBody: "Não foi possível carregar esta página. Tente de novo ou volte ao início.",
  tryAgain: "Tentar novamente",
  metaDescription:
    "SERIESAHOLIC, tracker de séries no estilo TV Time, com importação de dados e metadados via TMDB",
  appUnavailable: "Aplicação indisponível",
  globalErrorBody: "Ocorreu um erro crítico. Recarregue a página ou tente novamente em instantes.",
  loadError: "Erro ao carregar",
  addError: "Erro ao adicionar",
  cancelFailed: "Falha ao cancelar",
  cancelError: "Erro ao cancelar",
  clearFailed: "Falha ao limpar",
  clearError: "Erro ao limpar",
  saveFailed: "Falha ao salvar",
  saveError: "Erro ao salvar",
  monthOne: "mês",
  monthMany: "meses",
  dayOne: "dia",
  dayMany: "dias",
  hourOne: "hora",
  hourMany: "horas",
  yearOne: "ano",
  yearMany: "anos",
  formTitleRequired: "Título *",
  formStatusShow: "Status da série",
  formReturningOption: "Em produção / Returning",
  formEndedOption: "Finalizada / Ended",
  formCanceledOption: "Cancelada",
  formInProductionOption: "In Production",
  formPosterHint: "Poster (URL ou path TMDB)",
  formBackdropHint: "Backdrop (URL ou path TMDB)",
  formEpisodePlaceholder: "Nome do episódio",
  formAddEpisodePlus: "+ episódio",
  seasonsCount: "{n} temporadas",
  episodesCount: "{n} episódios",
  watchedOf: "{watched}/{total} episódios",
  deleteFailed: "Erro ao deletar",
  recommendError: "Erro ao gerar recomendações",
  episodesWithRuntime: "{n} episódios com duração · {hours} h nos últimos 7 dias",
  prevPage: "Anterior",
  nextPage: "Próxima",
  assimilatePrompt: "Deseja assimilar a alguma série existente ou criar nova?",
  searchPlaceholderShow: "Nome da série na biblioteca ou no TMDB",
  linkEpisodes: "Na sua biblioteca — vincular episódios",
  openShow: "Abrir série",
  link: "Vincular",
  onTmdb: "No TMDB — adicionar e vincular",
  alreadyInLibrary: "já na biblioteca",
  useThis: "Usar esta",
  createAndSave: "Criar série nova e gravar episódios",
  savingEpisodes: "Gravando episódios...",
  searchFailed: "Falha ao buscar séries",
  resolveError: "Erro ao resolver",
  footerCredit: "Davi Andrade. Tracker de séries.",
  footerSocial: "Redes sociais",
  opensInNewTab: "Abre em uma nova aba",
} as const;

const en: { [K in keyof typeof pt]: string } = {
  discover: "Discover",
  search: "Search",
  calendar: "Calendar",
  import: "Import",
  settings: "Settings",
  settingsPage: "Settings",
  preferences: "Preferences",
  profile: "Profile on daviandrade auth",
  guestEyebrow: "Temporary session",
  guestTitle: "You can use everything without an account",
  guestLogin: "Sign in and save",
  guestContinue: "Continue in this session",
  work: "My work",
  workBody:
    "I'm Davi Andrade. Seriesaholic is one of the portfolio apps, on the same account as the other projects.",
  student: "Asebili Student",
  instructor: "Asebili Instructor",
  library: "Library",
  home: "Home",
  login: "Sign in",
  signOut: "Sign out",
  toLight: "Switch to light theme",
  toDark: "Switch to dark theme",
  langPt: "Language: Portuguese",
  langEn: "Language: English",
  guestBody:
    "Adding shows, marking episodes, discovering, and importing works right now. It stays in this browser and disappears when the window closes. Sign in to keep it on your account and open it again whenever you want.",
  guestWork: "Seriesaholic is part of Davi Andrade's work.",
  portfolio: "Portfolio",
  continueBrowsing: "Continue without logging in",
  newShow: "New show",
  newShowSubtitle: "Add a title, images, seasons, and episodes by hand.",
  editShow: "Edit show",
  emptyLibrary: "Empty library",
  emptyLibraryBody: "Import your TV Time data, discover shows, or create one by hand.",
  discoverShows: "Discover shows",
  createShow: "Create show",
  importTvTime: "Import TV Time",
  watchNow: "Watch now",
  backlog: "Behind",
  upToDate: "Up to date",
  notStarted: "Added to list",
  finished: "Finished",
  dropped: "Dropped",
  seeAll: "See all",
  seeAllNamed: "See all — {title}",
  noPoster: "No poster",
  loadingUpcoming: "Looking up upcoming episodes...",
  upcomingEpisodes: "Upcoming episodes",
  forYou: "For you",
  forYouBody: "Based on your library. It only loads when you ask.",
  calculating: "Calculating...",
  seeRecommendations: "See recommendations",
  noRecommendations: "No recommendations from what you have already watched.",
  series: "Shows",
  episodes: "Episodes",
  time: "Time",
  fullStats: "Full stats",
  searchTitle: "Search shows",
  searchSubtitle: "Metadata via TMDB",
  searching: "Searching...",
  inLibrary: "In library",
  add: "Add",
  wantToWatch: "Want to watch",
  adding: "Adding...",
  discoverTitle: "Discover",
  discoverBased: "Recommended from {genres}",
  discoverCatalogCount: "{total} shows in the catalog, ready to add",
  discoverFallback: "Catalog of popular shows from TMDB",
  syncing: "Syncing...",
  refreshCatalog: "Refresh catalog",
  loading: "Loading...",
  loadingStats: "Loading stats...",
  discoverEmptyPersonal: "Import your TV Time shows to get personal recommendations.",
  discoverEmpty: "No new shows to discover.",
  fillCatalog: "Fill catalog now",
  tabAll: "All",
  tabTrending: "Trending",
  tabPopular: "Popular",
  tabTop: "Top rated",
  match: "{n}% match",
  calendarTitle: "Calendar",
  calendarSubtitle: "Episodes in the next 30 days",
  calendarEmpty: "No episodes scheduled. Add shows you are watching.",
  statsTitle: "Stats",
  statsSubtitle: "Your show-watching history",
  statsLoadError: "Could not load stats",
  watchTime: "Time watched",
  watchTimeNone: "No watched-episode history",
  watchTimeNoRuntime: "No runtime saved on episodes",
  watchTimeLast7: "{hours} hours in the last 7 days",
  hoursUnit: "Hours",
  episodesUnit: "Episodes",
  perWeekRuntime: "By week (episodes with a runtime only)",
  perWeek: "By week",
  perMonth: "By month",
  totalEpisodes: "Total episodes",
  episodesLast7: "{n} in the last 7 days",
  remainingEpisodes: "Episodes left",
  inStartedShows: "Across {n} started shows",
  catchUp: "Catch-up speed",
  catchUpValue: "{n} ep/week",
  catchUpBase: "Based on the last 2 months",
  timeToWatch: "Time left to watch",
  futureAirtime: "Future airtime",
  addedShows: "Shows added",
  stillInProduction: "{n} still in production",
  topGenres: "Top genres",
  genre: "Genre",
  noGenres: "Import shows to see genres.",
  marathons: "Longest binges",
  marathonShow: "Show",
  marathonEp: "Ep.",
  marathonHours: "Hours",
  noMarathons: "No binge recorded yet.",
  settingsSubtitle: "Library preferences and maintenance",
  dangerZone: "Danger zone",
  settingsDangerBefore: "Deletes",
  settingsDangerStrong: "every show",
  settingsDangerAfter:
    ", episode progress, custom shows, and import history. Use this before a clean reimport.",
  settingsItemLibrary: "Library and watched episodes",
  settingsItemImports: "TV Time import jobs and logs",
  settingsItemCatalogBefore: "The Discover catalog (TMDB) is",
  settingsItemCatalogNot: "not",
  settingsItemCatalogAfter: "deleted",
  typeConfirm: "Type {phrase} to enable:",
  erasing: "Deleting...",
  clearAll: "Clear all data",
  clearedBefore: "Data cleared. You can",
  importAgain: "import again",
  clearedOr: "or go back",
  clearedHome: "home",
  importTitle: "Import from TV Time",
  importSubtitle: "Supports GDPR export, TV Time Liberator, and JSON",
  viewHistory: "View history",
  clearData: "Clear data",
  importRunsOnServer:
    "The import runs on the server. You can close or refresh this page — progress continues and data already imported stays saved.",
  howToExport: "How to get your data",
  importStep1Before: "Open",
  importStep1After: "and download your export (.zip file)",
  importStep2Before: "Alternative: the",
  importStep2After: "extension (IMDB/TVDB format)",
  importStep3Before: "Set your TMDB API key in",
  importStep4: "Reimports only add new content and do not remove what is already there",
  importStep5: "Upload the file below",
  filesSelected: "{n} file(s) selected",
  clickToSelect: "Click to select files",
  importing: "Importing...",
  startImport: "Start import",
  pleaseWait: "Please wait...",
  cancelImport: "Cancel import",
  cancelling: "Cancelling...",
  importDone: "Import finished",
  importCancelled: "Import cancelled",
  importCancelledDetail: "Import cancelled. What was already imported stays in the library.",
  importError: "Import failed",
  formatDetected: "Detected format",
  showsAdded: "Shows added",
  newEpisodes: "New episodes",
  alreadyExisted: "Already existed",
  reviewAdded: "Review what was added",
  phaseParsing: "Reading file",
  phaseEpisodes: "Importing episodes",
  phaseWatchlist: "Importing watchlist",
  phaseDropped: "Importing dropped shows",
  phaseStatus: "Finishing",
  phaseComplete: "Done",
  notInLibrary: "This show is not in your library yet.",
  addToLibrary: "Add to library",
  unknownError: "Unknown error",
  edit: "Edit",
  deleting: "Deleting...",
  delete: "Delete",
  saving: "Saving...",
  dropShow: "Drop show",
  resumeWatching: "Resume watching",
  episodesHeading: "Episodes",
  deleteConfirm: "Delete this show and all progress?",
  finishedLabel: "Finished",
  droppedLabel: "Dropped",
  seasonName: "Season {n}",
  episodeName: "Episode {n}",
  markAll: "Mark all",
  unmarkAll: "Unmark all",
  formTitle: "Title",
  formStatus: "Status",
  formReturning: "In production",
  formEnded: "Ended",
  formCanceled: "Canceled",
  formOverview: "Overview",
  formPoster: "Poster",
  formBackdrop: "Backdrop",
  formPremiere: "Premiere",
  formGenres: "Genres (comma separated)",
  formSeasons: "Seasons and episodes",
  formSeason: "Season",
  formName: "Name",
  formNumber: "No.",
  formAirDate: "Date",
  formRuntime: "Min",
  formEpisode: "Episode",
  formSave: "Save changes",
  formSaving: "Saving...",
  formAddEpisode: "Episode",
  finishedTitle: "Finished shows",
  finishedCount: "{total} show(s) with every episode watched",
  finishedEmpty: "No finished shows yet.",
  backHome: "Back home",
  importsTitle: "Import history",
  importsSubtitle: "A record of each TV Time import",
  noImports: "No imports yet.",
  firstImport: "Run the first import",
  showsAddedShort: "+{n} shows",
  alreadyExistedShort: "({n} already existed)",
  importBack: "Back to history",
  importOf: "Import from {date}",
  newShows: "New shows",
  episodesAdded: "Episodes added",
  uniqueErrors: "Unique errors",
  uniqueWarningCount: "{n} unique warnings",
  showsInImport: "Shows in this import ({n})",
  noNewShows: "No new shows in this import.",
  episodesAddedCount: "+{n} episode(s)",
  failuresTitle: "Import failures ({n} pending)",
  failuresBody:
    "Each row below is exactly what did not come in. Match it to a library show or create a new one to save the watched episodes.",
  searchShow: "Search show",
  notFoundTitle: "Page not found",
  notFoundBody: "That address does not exist, or the content was removed.",
  errorTitle: "Something went wrong",
  errorBody: "This page could not be loaded. Try again or go back home.",
  tryAgain: "Try again",
  metaDescription:
    "SERIESAHOLIC, a TV Time style show tracker, with data import and metadata from TMDB",
  appUnavailable: "App unavailable",
  globalErrorBody: "A critical error occurred. Reload the page or try again in a moment.",
  loadError: "Could not load",
  addError: "Could not add",
  cancelFailed: "Could not cancel",
  cancelError: "Cancel failed",
  clearFailed: "Could not clear",
  clearError: "Clear failed",
  saveFailed: "Could not save",
  saveError: "Save failed",
  monthOne: "month",
  monthMany: "months",
  dayOne: "day",
  dayMany: "days",
  hourOne: "hour",
  hourMany: "hours",
  yearOne: "year",
  yearMany: "years",
  formTitleRequired: "Title *",
  formStatusShow: "Show status",
  formReturningOption: "In production / Returning",
  formEndedOption: "Ended",
  formCanceledOption: "Canceled",
  formInProductionOption: "In Production",
  formPosterHint: "Poster (URL or TMDB path)",
  formBackdropHint: "Backdrop (URL or TMDB path)",
  formEpisodePlaceholder: "Episode name",
  formAddEpisodePlus: "+ episode",
  seasonsCount: "{n} seasons",
  episodesCount: "{n} episodes",
  watchedOf: "{watched}/{total} episodes",
  deleteFailed: "Could not delete",
  recommendError: "Could not generate recommendations",
  episodesWithRuntime: "{n} episodes with a runtime · {hours} h in the last 7 days",
  prevPage: "Previous",
  nextPage: "Next",
  assimilatePrompt: "Match this to an existing show or create a new one?",
  searchPlaceholderShow: "Show name in your library or on TMDB",
  linkEpisodes: "In your library — link episodes",
  openShow: "Open show",
  link: "Link",
  onTmdb: "On TMDB — add and link",
  alreadyInLibrary: "already in library",
  useThis: "Use this",
  createAndSave: "Create a new show and save episodes",
  savingEpisodes: "Saving episodes...",
  searchFailed: "Could not search shows",
  resolveError: "Could not resolve",
  footerCredit: "Davi Andrade. Show tracker.",
  footerSocial: "Social links",
  opensInNewTab: "Opens in a new tab",
};

export const copy = { pt, en };
export type Language = keyof typeof copy;
export type CopyKey = keyof typeof pt;

export function translate(
  language: Language,
  key: CopyKey,
  vars?: Record<string, string | number>,
) {
  let text: string = copy[language][key];
  if (!vars) return text;
  for (const [name, value] of Object.entries(vars)) {
    text = text.replaceAll(`{${name}}`, String(value));
  }
  return text;
}

export function numberLocale(language: Language) {
  return language === "pt" ? "pt-BR" : "en-US";
}
