-- AlterTable
ALTER TABLE "Show" ADD COLUMN IF NOT EXISTS "genres" TEXT;
ALTER TABLE "Show" ADD COLUMN IF NOT EXISTS "tmdbStatus" TEXT;
ALTER TABLE "CatalogShow" ADD COLUMN IF NOT EXISTS "genres" TEXT;
